[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vibe-worldbuilding-mcp"
version = "1.0.0"
description = "A Model Context Protocol server for creating detailed fictional worlds with Claude, complete with automatic image generation"
authors = [{name = "Vibe Worldbuilding", email = "contact@example.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "mcp>=0.1.0",
    "google-generativeai>=0.3.0",
]

[project.urls]
Homepage = "https://github.com/example/vibe-worldbuilding-mcp"
Repository = "https://github.com/example/vibe-worldbuilding-mcp"

[project.scripts]
vibe-worldbuilding = "vibe_worldbuilding_server:main"